### ISSUE TITLE
关于jwt token的验证

### ISSUE THREAD

**Issue by damaohub** [Rock-1/koa2_Sequelize_project#1]
看了你的源码，登录的时候用JWT生成了token，之后怎么验证客户端提交过来的token是否合法呢，在你源码里没有找到相关内容，不是太懂，希望指导一下。谢谢

**Comment by Rock-1** [comment]
/**
 * 验证token
 * @param token
 * @param cb
 */
JwtSession.prototype.prverifySession =  async(token) => {
  try {
    let back =jwt.verify(token, '3mang');
    return back;
  } catch (error) {
    throw new Error(error)
  }
};

可以再中间件中调用这个方法进行验证

**Comment by damaohub** [comment]
嗯，谢谢
